Should study [open-context-jupyter/Open Context Measurements.ipynb at master · ekansa/open-context-jupyter](https://github.com/ekansa/open-context-jupyter/blob/master/notebooks/Open%20Context%20Measurements.ipynb)

May make use of [digitalbazaar/pyld: JSON-LD processor written in Python](https://github.com/digitalbazaar/pyld)

In [1]:
from itertools import islice
import json
from urllib.parse import urljoin
from urllib.parse import urlencode, quote_plus

import requests
from requests.packages.urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

from pyld import jsonld

import pandas as pd
import numpy as np
from pandas import DataFrame, Series, Index

In [2]:
def filter_none(d):
    return dict([(k,v) for (k,v) in d.items() if v is not None])


class OpenContextAPI(object):
    def __init__(self, api_url="https://opencontext.org/"):
        self.api_url = api_url
        self.session = requests.Session()
        retries = Retry(total=5,
                backoff_factor=0.3,
                status_forcelist=[ 500, 502, 503, 504 ])
        self.session.mount(self.api_url, HTTPAdapter(max_retries=retries))
        
    def _pager(self, url):
        while url:
            r = self.session.get(url)
            if r.status_code == 200:
                features = r.json().get('features', [])
                yield from features
            else:
                # to do: figure what to do when non-200 status code
                pass
            url = r.json().get('next-json', None)
        
        
    def projects_search(self, start=None, stop=None, rows=None):

        kw = filter_none({
            'start': start,
            'stop': stop,
            'rows': rows
        })
        
        url = urljoin(self.api_url, "projects-search.json") + "?" + urlencode(kw, quote_via=quote_plus)
        yield from self._pager(url)
        
                
    def project(self, project_id):
        
        url = urljoin(self.api_url, "projects/{}.json".format(project_id))
        r = self.session.get(url)
        if r.status_code == 200:
            return r.json()
        
    def subjects_search(self, project_id):
        """
        start with https://opencontext.org/subjects-search.json/?proj=12-presidio-of-san-francisco
        
        more complex possibilties:
        https://opencontext.org/subjects-search.json/?proj=12-presidio-of-san-francisco#10/37.8001/-122.4559/20/any/Google-Satellite.json
        """
        url = urljoin(self.api_url, "subjects-search.json/") + "?proj={}".format(project_id)
        print (url)
        yield from self._pager(url)

In [5]:
oc = OpenContextAPI("https://opencontext.org/")

In [6]:
features = oc.projects_search(rows=1000)

projects_df = DataFrame(list(islice(features,None)))
projects_df

,id,label,rdfs:isDefinedBy,type,category,geometry,properties
0,#record-1-of-116,Kenan Tepe,http://opencontext.org/projects/3DE4CD9C-259E-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-1-of-116', 'type': 'Poin...","{'id': '#rec-1-of-116', 'feature-type': 'item ..."
1,#record-2-of-116,"Architecture and Urbanism at Seyitömer Höyük, ...",http://opencontext.org/projects/347286db-b6c6-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-2-of-116', 'type': 'Poin...","{'id': '#rec-2-of-116', 'feature-type': 'item ..."
2,#record-3-of-116,Iraq Heritage Program,http://opencontext.org/projects/GHF1PRJ0000000025,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-3-of-116', 'type': 'Poin...","{'id': '#rec-3-of-116', 'feature-type': 'item ..."
3,#record-4-of-116,ARCE Sphinx Project 1979-1983 Archive,http://opencontext.org/projects/141e814a-ba2d-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-4-of-116', 'type': 'Poin...","{'id': '#rec-4-of-116', 'feature-type': 'item ..."
4,#record-5-of-116,China Ceramic Petrography Database,http://opencontext.org/projects/2c5addea-41d5-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-5-of-116', 'type': 'Poin...","{'id': '#rec-5-of-116', 'feature-type': 'item ..."
5,#record-6-of-116,Bade Museum,http://opencontext.org/projects/B4345F6A-F926-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-6-of-116', 'type': 'Poin...","{'id': '#rec-6-of-116', 'feature-type': 'item ..."
6,#record-7-of-116,Dhiban Excavation and Development Project,http://opencontext.org/projects/01D080DF-2F6B-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-7-of-116', 'type': 'Poin...","{'id': '#rec-7-of-116', 'feature-type': 'item ..."
7,#record-8-of-116,Zooarchaeology of Öküzini Cave,http://opencontext.org/projects/8894EEC0-DC96-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-8-of-116', 'type': 'Poin...","{'id': '#rec-8-of-116', 'feature-type': 'item ..."
8,#record-9-of-116,Murlo,http://opencontext.org/projects/DF043419-F23B-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-9-of-116', 'type': 'Poin...","{'id': '#rec-9-of-116', 'feature-type': 'item ..."
9,#record-11-of-116,Çukuriçi Höyük Zooarchaeology,http://opencontext.org/projects/BC90D462-6639-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-11-of-116', 'type': 'Poi...","{'id': '#rec-11-of-116', 'feature-type': 'item..."
10,#record-12-of-116,Köşk Höyük Faunal Data,http://opencontext.org/projects/05F5B702-2967-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-12-of-116', 'type': 'Poi...","{'id': '#rec-12-of-116', 'feature-type': 'item..."
11,#record-13-of-116,Zooarchaeology of Karain Cave B,http://opencontext.org/projects/731B0670-CE2A-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-13-of-116', 'type': 'Poi...","{'id': '#rec-13-of-116', 'feature-type': 'item..."
12,#record-14-of-116,Çatalhöyük Zooarchaeology,http://opencontext.org/projects/1B426F7C-99EC-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-14-of-116', 'type': 'Poi...","{'id': '#rec-14-of-116', 'feature-type': 'item..."
13,#record-16-of-116,Hacksilber Project,http://opencontext.org/projects/CF179695-1E6A-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-16-of-116', 'type': 'Poi...","{'id': '#rec-16-of-116', 'feature-type': 'item..."
14,#record-18-of-116,Petra Great Temple Excavations,http://opencontext.org/projects/A5DDBEA2-B3C8-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-18-of-116', 'type': 'Poi...","{'id': '#rec-18-of-116', 'feature-type': 'item..."
15,#record-19-of-116,Biometrical Database of European Aurochs and D...,http://opencontext.org/projects/1816A043-92E2-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-19-of-116', 'type': 'Poi...","{'id': '#rec-19-of-116', 'feature-type': 'item..."
16,#record-20-of-116,Erbaba Höyük and Suberde Zooarchaeology,http://opencontext.org/projects/CDD40C27-62ED-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-20-of-116', 'type': 'Poi...","{'id': '#rec-20-of-116', 'feature-type': 'item..."
17,#record-22-of-116,Animal remains from Forcello,http://opencontext.org/projects/bdc6cb19-e739-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-22-of-116', 'type': 'Poi...","{'id': '#rec-22-of-116', 'feature-type': 'item..."
18,#record-23-of-116,Giza Botanical Database,http://opencontext.org/projects/10aa84ad-c5de-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-23-of-116', 'type': 'Poi...","{'id': '#rec-23-of-116', 'feature-type': 'item..."
19,#record-24-of-116,Idalion,http://opencontext.org/projects/df8e4efd-e06b-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-24-of-116', 'type': 'Poi...","{'id': '#rec-24-of-116', 'feature-type': 'item..."
20,#record-27-of-116,Ilıpınar Zooarchaeology,http://opencontext.org/projects/D297CD29-50CA-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-27-of-116', 'type': 'Poi...","{'id': '#rec-27-of-116', 'feature-type': 'item..."
21,#record-29-of-116,"Faunal Data from Al-Wu’ayra Fortress, Petra Va...",http://opencontext.org/projects/ea62c747-f3ae-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-29-of-116', 'type': 'Poi...","{'id': '#rec-29-of-116', 'feature-type': 'item..."
22,#record-30-of-116,Barçın Höyük Zooarchaeology,http://opencontext.org/projects/74749949-4FD4-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-30-of-116', 'type': 'Poi...","{'id': '#rec-30-of-116', 'feature-type': 'item..."
23,#record-31-of-116,Virtual Valdivia,http://opencontext.org/projects/d3bed915-947d-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-31-of-116', 'type': 'Poi...","{'id': '#rec-31-of-116', 'feature-type': 'item..."
24,#record-34-of-116,Mikt’sqaq Angayuk Finds,http://opencontext.org/projects/CF6E1364-D6EF-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-34-of-116', 'type': 'Poi...","{'id': '#rec-34-of-116', 'feature-type': 'item..."
25,#record-35-of-116,Georgia Archaeological Site File (GASF),http://opencontext.org/projects/64013C33-4039-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-35-of-116', 'type': 'Poi...","{'id': '#rec-35-of-116', 'feature-type': 'item..."
26,#record-36-of-116,Northern Mesopotamian Pig Husbandry (Late Neol...,http://opencontext.org/projects/d1c85af4-c870-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-36-of-116', 'type': 'Poi...","{'id': '#rec-36-of-116', 'feature-type': 'item..."
27,#record-37-of-116,Faunal Data from Neolithic Menteşe,http://opencontext.org/projects/42EAD4DB-BAED-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-37-of-116', 'type': 'Poi...","{'id': '#rec-37-of-116', 'feature-type': 'item..."
28,#record-38-of-116,Chogha Mish Fauna,http://opencontext.org/projects/497ADEAD-0C2A-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-38-of-116', 'type': 'Poi...","{'id': '#rec-38-of-116', 'feature-type': 'item..."
29,#record-39-of-116,"Ceramics, Trade, Provenience and Geology: Cypr...",http://opencontext.org/projects/ABABD13C-A69F-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-39-of-116', 'type': 'Poi...","{'id': '#rec-39-of-116', 'feature-type': 'item..."
...,...,...,...,...,...,...,...
52,#record-67-of-116,Presidio of San Francisco,http://opencontext.org/projects/C5B4F73B-5EF8-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-67-of-116', 'type': 'Poi...","{'id': '#rec-67-of-116', 'feature-type': 'item..."
53,#record-68-of-116,Pennsylvania Site Files,http://opencontext.org/projects/766698E3-2E79-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-68-of-116', 'type': 'Poi...","{'id': '#rec-68-of-116', 'feature-type': 'item..."
54,#record-69-of-116,Ohio Site Files,http://opencontext.org/projects/EDDA846F-7225-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-69-of-116', 'type': 'Poi...","{'id': '#rec-69-of-116', 'feature-type': 'item..."
55,#record-70-of-116,Oracle Bones in East Asia,http://opencontext.org/projects/27e90af3-6bf7-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-70-of-116', 'type': 'Poi...","{'id': '#rec-70-of-116', 'feature-type': 'item..."
56,#record-72-of-116,Harvard Peabody Mus. Zooarchaeology,http://opencontext.org/projects/HPeaZooPRJ0000...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-72-of-116', 'type': 'Poi...","{'id': '#rec-72-of-116', 'feature-type': 'item..."
57,#record-73-of-116,Traces in the Lost Landscape,http://opencontext.org/projects/23696274-1f6d-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-73-of-116', 'type': 'Poi...","{'id': '#rec-73-of-116', 'feature-type': 'item..."
58,#record-74-of-116,Kuthodaw Pagoda Inscriptions,http://opencontext.org/projects/b6de18c6-bba8-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-74-of-116', 'type': 'Poi...","{'id': '#rec-74-of-116', 'feature-type': 'item..."
59,#record-75-of-116,Images Documenting The Ottoman Tiles of the Fa...,http://opencontext.org/projects/2bc1f77d-fe36-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-75-of-116', 'type': 'Poi...","{'id': '#rec-75-of-116', 'feature-type': 'item..."
60,#record-77-of-116,"Digital Companion to ""A Preliminary Analysis o...",http://opencontext.org/projects/a820af0c-ab4d-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-77-of-116', 'type': 'Poi...","{'id': '#rec-77-of-116', 'feature-type': 'item..."
61,#record-79-of-116,The Gabii Project,http://opencontext.org/projects/3585b372-8d2d-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-79-of-116', 'type': 'Poi...","{'id': '#rec-79-of-116', 'feature-type': 'item..."
62,#record-84-of-116,"Lake Carlos Beach Site, 1992 and 1996",http://opencontext.org/projects/MHS1PRJ0000000021,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-84-of-116', 'type': 'Poi...","{'id': '#rec-84-of-116', 'feature-type': 'item..."
63,#record-86-of-116,Avkat Archaeological Project,http://opencontext.org/projects/02b55e8c-e9b1-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-86-of-116', 'type': 'Poi...","{'id': '#rec-86-of-116', 'feature-type': 'item..."
64,#record-88-of-116,Digital Companion to 'Late Nineteenth and Earl...,http://opencontext.org/projects/8ae150fc-50f1-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-88-of-116', 'type': 'Poi...","{'id': '#rec-88-of-116', 'feature-type': 'item..."
65,#record-89-of-116,Biometry of Iron Age II and Hellenistic Period...,http://opencontext.org/projects/646b7034-07b7-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-89-of-116', 'type': 'Poi...","{'id': '#rec-89-of-116', 'feature-type': 'item..."
66,#record-90-of-116,Virginia Site Files,http://opencontext.org/projects/AF0D2F67-2EAB-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-90-of-116', 'type': 'Poi...","{'id': '#rec-90-of-116', 'feature-type': 'item..."
67,#record-91-of-116,Historic Fort Snelling,http://opencontext.org/projects/fab0532a-2953-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-91-of-116', 'type': 'Poi...","{'id': '#rec-91-of-116', 'feature-type': 'item..."
68,#record-93-of-116,Louisiana Site Files,http://opencontext.org/projects/56110B30-3C18-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-93-of-116', 'type': 'Poi...","{'id': '#rec-93-of-116', 'feature-type': 'item..."
69,#record-94-of-116,Alabama Site Files,http://opencontext.org/projects/F905BD53-C843-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-94-of-116', 'type': 'Poi...","{'id': '#rec-94-of-116', 'feature-type': 'item..."
70,#record-95-of-116,Tennessee Site Files,http://opencontext.org/projects/7f82f3f3-04d2-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-95-of-116', 'type': 'Poi...","{'id': '#rec-95-of-116', 'feature-type': 'item..."
71,#record-96-of-116,Rough Cilicia,http://opencontext.org/projects/295B5BF4-0F44-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-96-of-116', 'type': 'Poi...","{'id': '#rec-96-of-116', 'feature-type': 'item..."
72,#record-97-of-116,North Carolina Site Files,http://opencontext.org/projects/5F2D4172-D823-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-97-of-116', 'type': 'Poi...","{'id': '#rec-97-of-116', 'feature-type': 'item..."
73,#record-98-of-116,Maryland Site Files,http://opencontext.org/projects/F9970276-8636-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-98-of-116', 'type': 'Poi...","{'id': '#rec-98-of-116', 'feature-type': 'item..."
74,#record-99-of-116,Images Documenting Ethnoarchaeology in the Env...,http://opencontext.org/projects/04df4d32-9843-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-99-of-116', 'type': 'Poi...","{'id': '#rec-99-of-116', 'feature-type': 'item..."
75,#record-100-of-116,Hazor: Zooarchaeology,http://opencontext.org/projects/HazorZooPRJ000...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-100-of-116', 'type': 'Po...","{'id': '#rec-100-of-116', 'feature-type': 'ite..."
76,#record-103-of-116,San Diego Archaeological Center,http://opencontext.org/projects/3FAAA477-5572-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-103-of-116', 'type': 'Po...","{'id': '#rec-103-of-116', 'feature-type': 'ite..."
77,#record-104-of-116,Corneal Ulceration in South East Asia,http://opencontext.org/projects/DTrev1PRJ00000...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-104-of-116', 'type': 'Po...","{'id': '#rec-104-of-116', 'feature-type': 'ite..."
78,#record-105-of-116,Hayonim: Micromorphology,http://opencontext.org/projects/GBHayPRJ000000...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-105-of-116', 'type': 'Po...","{'id': '#rec-105-of-116', 'feature-type': 'ite..."
79,#record-106-of-116,Images Documenting Looting in the North Cemete...,http://opencontext.org/projects/8859aa10-c0c4-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-106-of-116', 'type': 'Po...","{'id': '#rec-106-of-116', 'feature-type': 'ite..."
80,#record-107-of-116,Geissenklosterle: Micromorphology,http://opencontext.org/projects/PGold1PRJ00000...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-107-of-116', 'type': 'Po...","{'id': '#rec-107-of-116', 'feature-type': 'ite..."
81,#record-113-of-116,Excavations at Polis,http://opencontext.org/projects/766d9fd5-2175-...,Feature,oc-api:geo-record,"{'id': '#geo-rec-geom-113-of-116', 'type': 'Po...","{'id': '#rec-113-of-116', 'feature-type': 'ite..."

In [7]:
projects_df.iloc[0]['properties']['href']

'https://opencontext.org/projects/3DE4CD9C-259E-4C14-9B03-8B10454BA66E'

In [8]:
print(", ".join([f"'{id_}'" for id_ in list(projects_df.apply(lambda row: row['properties']['href'].split('/')[-1], axis=1))]))

'3DE4CD9C-259E-4C14-9B03-8B10454BA66E', '347286db-b6c6-4fd2-b3bd-b50316b0cb9f', 'GHF1PRJ0000000025', '141e814a-ba2d-4560-879f-80f1afb019e9', '2c5addea-41d5-4941-b2bd-672bc1e60448', 'B4345F6A-F926-4062-144E-3FBC175CC7B6', '01D080DF-2F6B-4F59-BCF0-87543AC89574', '8894EEC0-DC96-4304-1EFC-4572FD91717A', 'DF043419-F23B-41DA-7E4D-EE52AF22F92F', 'BC90D462-6639-4087-8527-6BB9E528E07D', '05F5B702-2967-49B1-FEAA-9B2AA0184513', '731B0670-CE2A-414A-8EF6-9C050A1C60F5', '1B426F7C-99EC-4322-4069-E8DBD927CCF1', 'CF179695-1E6A-440F-1DDB-4FEA7B02A5B5', 'A5DDBEA2-B3C8-43F9-8151-33343CBDC857', '1816A043-92E2-471D-A23D-AAC58695D0D3', 'CDD40C27-62ED-4966-AF3D-E781DD0D4846', 'bdc6cb19-e739-404b-8b4f-eeeaae3b8aae', '10aa84ad-c5de-4e79-89ce-d83b75ed72b5', 'df8e4efd-e06b-4b0b-a056-08b6fd199536', 'D297CD29-50CA-4B2C-4A07-498ADF3AF487', 'ea62c747-f3ae-4972-8f83-f8aecfcfbaea', '74749949-4FD4-4C3E-C830-5AA75703E08E', 'd3bed915-947d-4c1a-8c9a-b7723f03d21a', 'CF6E1364-D6EF-4042-B726-82CFB73F7C9D', '64013C33-4039-46C9-609A-A758CE51CA49', 'd1c85af4-c870-488a-865b-b3cf784cfc60', '42EAD4DB-BAED-4A58-9B9B-7EC85266D2A9', '497ADEAD-0C2A-4C62-FEEF-9079FB09B1A5', 'ABABD13C-A69F-499E-CA7F-5118F3684E4D', 'A3CBADB6-6CD4-4099-9FE2-A33757EAB749', '4B16F48E-6F5D-41E0-F568-FCE64BE6D3FA', '3F6DCD13-A476-488E-ED10-47D25513FCB2', '0cea2f4a-84cb-4083-8c66-5191628abe67', 'D6B25EC9-2884-4E3C-00E8-0C5A6472FA63', '81204AF8-127C-4686-E9B0-1202C3A47959', '59E7BFBC-2557-4FE4-FC14-284ED10D903D', 'F05ACE4F-9B55-48A0-D640-5276B8B899C7', 'B1DAC335-4DC6-4A57-622E-75BF28BA598D', 'D42FC0EB-61B0-4937-700E-4EFEAB008677', '3', 'cbd24bbb-c6fc-44ed-bd67-6f844f120ad5', '4B5721E9-2BB3-423F-5D04-1B948FA65FAB', 'B7F85EB6-4BF5-43FA-98E7-FF8FAF1AA452', '81d1157d-28f4-46ff-98dd-94899c1688f8', '8492AEC3-E406-44C6-03CA-2BF280D8F5B0', 'd75ef68a-0e23-458c-976d-286d83c13013', '8F947319-3C69-4847-B7A2-09E00ED90B32', '416A274C-CF88-4471-3E31-93DB825E9E4A', 'B7047162-6906-4A5E-13C0-B5B86A108510', '0EE6A09E-62E5-45F0-1CB9-F5CDA44F4D9E', 'TESTPRJ0000000004', 'C5B4F73B-5EF8-4099-590E-B0275EDBA2A7', '766698E3-2E79-4A78-B0BC-245FF435BBBD', 'EDDA846F-7225-495E-AB77-7314C256449A', '27e90af3-6bf7-4da1-a1c3-7b2f744e8cf7', 'HPeaZooPRJ0000000012', '23696274-1f6d-44ca-9697-36b9d5e3fe5d', 'b6de18c6-bba8-4b53-9d9e-3eea4b794268', '2bc1f77d-fe36-41eb-99b9-c0261edb4f18', 'a820af0c-ab4d-4518-ba91-ac3bede21c4d', '3585b372-8d2d-436c-9a4c-b5c10fce3ccd', 'MHS1PRJ0000000021', '02b55e8c-e9b1-49e5-8edf-0afeea10e2be', '8ae150fc-50f1-4e60-9dd3-df594b02ddd4', '646b7034-07b7-4971-8d89-ebe37dda4cd2', 'AF0D2F67-2EAB-4C28-9C61-0F019CBF628E', 'fab0532a-2953-4f13-aa97-8a9d7e992dbe', '56110B30-3C18-49F9-BDA9-550FE8E28450', 'F905BD53-C843-4349-0A46-48FF32B5F1BE', '7f82f3f3-04d2-47c3-b0a9-21aa28294d25', '295B5BF4-0F44-4698-80CD-7A39CB6F133D', '5F2D4172-D823-4F7F-D3A8-4BD68ED1369D', 'F9970276-8636-478D-A3F0-08CC7EFEAD4F', '04df4d32-9843-4edc-9361-132474acaa5f', 'HazorZooPRJ0000000010', '3FAAA477-5572-4B05-8DC1-CA264FE1FC10', 'DTrev1PRJ0000000014', 'GBHayPRJ0000000005', '8859aa10-c0c4-42ad-993b-cc9d79800d8e', 'PGold1PRJ0000000005', '766d9fd5-2175-41e3-b7c9-7eba6777f1f0'

I don't understand why we get only 77 results and not 108.

# Studying a specific project

https://opencontext.org/projects/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7  --> Presidio project

aka https://opencontext.org/projects/12-presidio-of-san-francisco

In [9]:
projects_df.iloc[0].properties.get('uri')

'http://opencontext.org/projects/3DE4CD9C-259E-4C14-9B03-8B10454BA66E'

In [10]:
import json

k = projects_df.apply(lambda row: row.properties.get('uri'), axis=1)
k.to_dict()

{0: 'http://opencontext.org/projects/3DE4CD9C-259E-4C14-9B03-8B10454BA66E',
 1: 'http://opencontext.org/projects/347286db-b6c6-4fd2-b3bd-b50316b0cb9f',
 2: 'http://opencontext.org/projects/GHF1PRJ0000000025',
 3: 'http://opencontext.org/projects/141e814a-ba2d-4560-879f-80f1afb019e9',
 4: 'http://opencontext.org/projects/2c5addea-41d5-4941-b2bd-672bc1e60448',
 5: 'http://opencontext.org/projects/B4345F6A-F926-4062-144E-3FBC175CC7B6',
 6: 'http://opencontext.org/projects/01D080DF-2F6B-4F59-BCF0-87543AC89574',
 7: 'http://opencontext.org/projects/8894EEC0-DC96-4304-1EFC-4572FD91717A',
 8: 'http://opencontext.org/projects/DF043419-F23B-41DA-7E4D-EE52AF22F92F',
 9: 'http://opencontext.org/projects/BC90D462-6639-4087-8527-6BB9E528E07D',
 10: 'http://opencontext.org/projects/05F5B702-2967-49B1-FEAA-9B2AA0184513',
 11: 'http://opencontext.org/projects/731B0670-CE2A-414A-8EF6-9C050A1C60F5',
 12: 'http://opencontext.org/projects/1B426F7C-99EC-4322-4069-E8DBD927CCF1',
 13: 'http://opencontext.org/projects/CF179695-1E6A-440F-1DDB-4FEA7B02A5B5',
 14: 'http://opencontext.org/projects/A5DDBEA2-B3C8-43F9-8151-33343CBDC857',
 15: 'http://opencontext.org/projects/1816A043-92E2-471D-A23D-AAC58695D0D3',
 16: 'http://opencontext.org/projects/CDD40C27-62ED-4966-AF3D-E781DD0D4846',
 17: 'http://opencontext.org/projects/bdc6cb19-e739-404b-8b4f-eeeaae3b8aae',
 18: 'http://opencontext.org/projects/10aa84ad-c5de-4e79-89ce-d83b75ed72b5',
 19: 'http://opencontext.org/projects/df8e4efd-e06b-4b0b-a056-08b6fd199536',
 20: 'http://opencontext.org/projects/D297CD29-50CA-4B2C-4A07-498ADF3AF487',
 21: 'http://opencontext.org/projects/ea62c747-f3ae-4972-8f83-f8aecfcfbaea',
 22: 'http://opencontext.org/projects/74749949-4FD4-4C3E-C830-5AA75703E08E',
 23: 'http://opencontext.org/projects/d3bed915-947d-4c1a-8c9a-b7723f03d21a',
 24: 'http://opencontext.org/projects/CF6E1364-D6EF-4042-B726-82CFB73F7C9D',
 25: 'http://opencontext.org/projects/64013C33-4039-46C9-609A-A758CE51CA49',
 26: 'http://opencontext.org/projects/d1c85af4-c870-488a-865b-b3cf784cfc60',
 27: 'http://opencontext.org/projects/42EAD4DB-BAED-4A58-9B9B-7EC85266D2A9',
 28: 'http://opencontext.org/projects/497ADEAD-0C2A-4C62-FEEF-9079FB09B1A5',
 29: 'http://opencontext.org/projects/ABABD13C-A69F-499E-CA7F-5118F3684E4D',
 30: 'http://opencontext.org/projects/A3CBADB6-6CD4-4099-9FE2-A33757EAB749',
 31: 'http://opencontext.org/projects/4B16F48E-6F5D-41E0-F568-FCE64BE6D3FA',
 32: 'http://opencontext.org/projects/3F6DCD13-A476-488E-ED10-47D25513FCB2',
 33: 'http://opencontext.org/projects/0cea2f4a-84cb-4083-8c66-5191628abe67',
 34: 'http://opencontext.org/projects/D6B25EC9-2884-4E3C-00E8-0C5A6472FA63',
 35: 'http://opencontext.org/projects/81204AF8-127C-4686-E9B0-1202C3A47959',
 36: 'http://opencontext.org/projects/59E7BFBC-2557-4FE4-FC14-284ED10D903D',
 37: 'http://opencontext.org/projects/F05ACE4F-9B55-48A0-D640-5276B8B899C7',
 38: 'http://opencontext.org/projects/B1DAC335-4DC6-4A57-622E-75BF28BA598D',
 39: 'http://opencontext.org/projects/D42FC0EB-61B0-4937-700E-4EFEAB008677',
 40: 'http://opencontext.org/projects/3',
 41: 'http://opencontext.org/projects/cbd24bbb-c6fc-44ed-bd67-6f844f120ad5',
 42: 'http://opencontext.org/projects/4B5721E9-2BB3-423F-5D04-1B948FA65FAB',
 43: 'http://opencontext.org/projects/B7F85EB6-4BF5-43FA-98E7-FF8FAF1AA452',
 44: 'http://opencontext.org/projects/81d1157d-28f4-46ff-98dd-94899c1688f8',
 45: 'http://opencontext.org/projects/8492AEC3-E406-44C6-03CA-2BF280D8F5B0',
 46: 'http://opencontext.org/projects/d75ef68a-0e23-458c-976d-286d83c13013',
 47: 'http://opencontext.org/projects/8F947319-3C69-4847-B7A2-09E00ED90B32',
 48: 'http://opencontext.org/projects/416A274C-CF88-4471-3E31-93DB825E9E4A',
 49: 'http://opencontext.org/projects/B7047162-6906-4A5E-13C0-B5B86A108510',
 50: 'http://opencontext.org/projects/0EE6A09E-62E5-45F0-1CB9-F5CDA44F4D9E',
 51: 'http://opencontext.org/projects/TESTPRJ0000000004',
 52: 'http://opencontext.org/projects/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7',
 53: 'http://opencontext.org/projects/766698E3-2E79-4A78-B0BC-245FF435BBBD',
 54: 'http://opencontext.org/projects/EDDA846F-7225-495E-AB77-7314C256449A',
 55: 'http://opencontext.org/projects/27e90af3-6bf7-4da1-a1c3-7b2f744e8cf7',
 56: 'http://opencontext.org/projects/HPeaZooPRJ0000000012',
 57: 'http://opencontext.org/projects/23696274-1f6d-44ca-9697-36b9d5e3fe5d',
 58: 'http://opencontext.org/projects/b6de18c6-bba8-4b53-9d9e-3eea4b794268',
 59: 'http://opencontext.org/projects/2bc1f77d-fe36-41eb-99b9-c0261edb4f18',
 60: 'http://opencontext.org/projects/a820af0c-ab4d-4518-ba91-ac3bede21c4d',
 61: 'http://opencontext.org/projects/3585b372-8d2d-436c-9a4c-b5c10fce3ccd',
 62: 'http://opencontext.org/projects/MHS1PRJ0000000021',
 63: 'http://opencontext.org/projects/02b55e8c-e9b1-49e5-8edf-0afeea10e2be',
 64: 'http://opencontext.org/projects/8ae150fc-50f1-4e60-9dd3-df594b02ddd4',
 65: 'http://opencontext.org/projects/646b7034-07b7-4971-8d89-ebe37dda4cd2',
 66: 'http://opencontext.org/projects/AF0D2F67-2EAB-4C28-9C61-0F019CBF628E',
 67: 'http://opencontext.org/projects/fab0532a-2953-4f13-aa97-8a9d7e992dbe',
 68: 'http://opencontext.org/projects/56110B30-3C18-49F9-BDA9-550FE8E28450',
 69: 'http://opencontext.org/projects/F905BD53-C843-4349-0A46-48FF32B5F1BE',
 70: 'http://opencontext.org/projects/7f82f3f3-04d2-47c3-b0a9-21aa28294d25',
 71: 'http://opencontext.org/projects/295B5BF4-0F44-4698-80CD-7A39CB6F133D',
 72: 'http://opencontext.org/projects/5F2D4172-D823-4F7F-D3A8-4BD68ED1369D',
 73: 'http://opencontext.org/projects/F9970276-8636-478D-A3F0-08CC7EFEAD4F',
 74: 'http://opencontext.org/projects/04df4d32-9843-4edc-9361-132474acaa5f',
 75: 'http://opencontext.org/projects/HazorZooPRJ0000000010',
 76: 'http://opencontext.org/projects/3FAAA477-5572-4B05-8DC1-CA264FE1FC10',
 77: 'http://opencontext.org/projects/DTrev1PRJ0000000014',
 78: 'http://opencontext.org/projects/GBHayPRJ0000000005',
 79: 'http://opencontext.org/projects/8859aa10-c0c4-42ad-993b-cc9d79800d8e',
 80: 'http://opencontext.org/projects/PGold1PRJ0000000005',
 81: 'http://opencontext.org/projects/766d9fd5-2175-41e3-b7c9-7eba6777f1f0'}

In [11]:
#presidio project is not in that list

projects_df[projects_df.apply(lambda row: row.properties.get('uri'), axis=1) == 'https://opencontext.org/projects/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7']

Empty DataFrame
Columns: [id, label, rdfs:isDefinedBy, type, category, geometry, properties]
Index: []

In [12]:
oc.project('C5B4F73B-5EF8-4099-590E-B0275EDBA2A7')

{'@context': ['https://doi.org/10.6078/M7P848VC',
  'http://geojson.org/geojson-ld/geojson-context.jsonld',
  'https://opencontext.org/contexts/project-vocabs/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7.json'],
 'id': 'http://opencontext.org/projects/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7',
 'uuid': 'C5B4F73B-5EF8-4099-590E-B0275EDBA2A7',
 'slug': '12-presidio-of-san-francisco',
 'label': 'Presidio of San Francisco',
 'description': 'Ongoing investigations of El Presidio de San Francisco and other archaeological resources at the Presidio of San Francisco',
 'dc-terms:abstract': "<p>The Presidio of San Francisco is a national park site measuring 1491 acres, administered jointly by the Presidio Trust and the National Park Service. The Presidio was in continuous use as a military post from 1776 to 1994, serving under the flags of Spain, Mexico, and the United States. During the transition from an active Army Post to a National Park, an update to the Presidio\x92s National Historic Landmark designation was undertaken. This effort documented nearly 4000 sites, buildings, structures, and objects as contributing features to the Landmark, and the Presidio was reclassified as a National Historic Landmark District\x97the highest designation. Included were 54 locations of predicted archaeological significance, including forgotten cemeteries, shipwrecks, native shell mounds, coastal fortifications and the cornerstone of the Presidio Trust\x92s Archaeology Program\x97the Spanish Colonial site <em>El Presidio de San Francisco</em>. Due to the Presidio\x92s long continuum of history from colonialism till the Cold War, there is an array of important sites beyond the temporal and spatial boundaries of El Presidio which make this park exceptional as an archaeological resource.</p>  \r\n\r\n<p>The Presidio Archaeology Lab is home to the Archaeology Program of the Presidio Trust. It is the nexus of all archaeological efforts at the Presidio where a lively community engages in the stewardship of the Presidio\x92s rich archaeological heritage. <em>El Presidio de San Francisco</em> is the only one of four Spanish fortifications and twenty-one missions in California located in a National Park. This results in an opportunity to reach and teach a large audience about this irreplaceable resource, the Spanish Colonial episode in our nation\x92s heritage, as well as the methods of archaeology, history, and related sciences. The mission of the Presidio Archaeology Lab is to demonstrate leadership in the field of archaeology and enhance the understanding of our shared cultural heritage.</p>    \r\n\r\n<p>The goals of the Presidio Archaeology Lab are:</p>\r\n<ul>\r\n    <li>To create a compelling destination at the site of <em>El Presidio de San Francisco</em>, one that instills visitors with the imaginative tools necessary to explore a broader range of the American experience.</li>\r\n    <li>To encourage a sense of collective ownership for the past, and this park, by involving diverse members of the public in all our programs and enabling them to make their own connections to this place.</li>\r\n    <li>To preserve the integrity of the archaeological sites, features, and artifacts, which form the foundation of our programs, ensuring that authentic experiences are available to future generations.</li>\r\n</ul>\r\n\r\n<br/>\r\n<p class='subHeader'>Additional Web Resources:</p>\r\n<ul>\r\n    <li><a href='http://www.presidio.gov/history/archaeology/'>Presidio Archaeology Lab Website</a></li> \r\n    <li><a href='http://library.presidio.gov/archive/documents/Levantar-pt1.pdf'>Levantar, The Presidio of San Francisco Archaeological Management Strategy</a> (PDF)</li>\r\n    <li><a href='http://www.presidio.gov/'>Presidio Trust Website</a></li> \r\n</ul>\r\n\r\n<br/>\r\n<p class='subHeader'>Additional Web Resources:</p>\r\n<p>Presidio Archaeology Lab<br/>\r\nPresidio Trust<br/> \r\nPO Box 29052<br/>\r\nSan Francisco, CA 94129 USA<br/>\r\nPhone: (415) 561-ARCH<br/>\r\nFax: (415) 561-5089<br/>\r\narchaeology@presidiotrust.gov<br/> \r\n</p>",
 'bibo:status': [{'id': 'http://opencontext.org/vocabularies/oc-general/edit-level-3',
   'slug': 'oc-gen-edit-level-3',
   'label': 'Managing editor reviewed'},
  {'id': 'http://purl.org/ontology/bibo/status/peerReviewed',
   'slug': 'bibo-status-peerreviewed',
   'label': 'Peer reviewed'}],
 'features': [{'id': '#geo-1',
   'geometry': {'id': '#geo-geom-1',
    'type': 'Point',
    'coordinates': [-122.455925, 37.800154]},
   'properties': {'location-note': 'Location data available with no intentional reduction in precision.',
    'id': '#geo-props-1',
    'href': 'http://opencontext.org/projects/C5B4F73B-5EF8-4099-590E-B0275EDBA2A7',
    'reference-label': 'Presidio of San Francisco',
    'type': 'oc-gen:geo-coverage',
    'note': 'Project geographic coverage                         summarized from geospatial data                         describing subjects published                         with this project.',
    'reference-type': 'specified'},
   'type': 'Feature'}],
 'type': 'FeatureCollection',
 'foaf:depiction': [{'id': 'http://artiraq.org/static/opencontext/presidio-of-san-francisco/heros/presidio-bldg39-hero.jpg',
   'type': 'oc-gen:hero',
   'dc-terms:hasFormat': 'http://purl.org/NET/mediatypes/image/jpeg',
   'dcat:size': 366385.0}],
 'dc-terms:title': 'Presidio of San Francisco',
 'dc-terms:issued': '2010-01-25',
 'dc-terms:modified': '2014-05-19',
 'dc-terms:creator': [],
 'dc-terms:isReferencedBy': [{'id': 'http://opencontext.org/tables/2edc4d5eeffe18944c973b242c555cbe',
   'slug': '12-presidio-chickens',
   'label': 'Presidio Chickens'},
  {'id': 'http://opencontext.org/tables/be34b6fb5f62535d07eae6b6cac3c73e',
   'slug': '12-presidio-building-39-animal-bones',
   'label': 'Presidio Building 39 Animal Bones'}],
 'dc-terms:spatial': [{'id': 'http://www.geonames.org/5391959',
   'slug': 'geonames-5391959',
   'label': 'San Francisco'},
  {'id': 'http://www.geonames.org/5332921',
   'slug': 'geonames-5332921',
   'label': 'California'}],
 'dc-terms:subject': [{'id': 'http://id.loc.gov/authorities/subjects/sh85006513',
   'slug': 'loc-sh-sh85006513',
   'label': 'Historical archaeology'},
  {'id': 'http://en.wikipedia.org/wiki/History_of_California',
   'slug': 'wiki-history-of-california',
   'label': 'History of California'},
  {'id': 'http://id.loc.gov/authorities/subjects/sh85140642',
   'slug': 'loc-sh-sh85140642',
   'label': 'United States. Army--History'},
  {'id': 'http://id.loc.gov/authorities/subjects/sh99005758',
   'slug': 'loc-sh-sh99005758',
   'label': 'Education'}],
 'owl:sameAs': [{'id': 'https://n2t.net/ark:/28722/k21n86s85'}]}

* Data Records
* Media

In [13]:
# this takes a while to get through all 1000+ records 
# limit this to 50

for (i, record) in enumerate(islice(oc.subjects_search('12-presidio-of-san-francisco'),50)):
    print ("\r", i, end="")

https://opencontext.org/subjects-search.json/?proj=12-presidio-of-san-francisco
 49